name: Instalflow CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      NODE_ENV: ${{ secrets.NODE_ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm run db:generate

      - name: Run ESLint
        run: pnpm run lint

      - name: Cleanup database
        run: pnpm run db:cleanup

      - name: Push database schema
        run: pnpm run db:push --accept-data-loss

      # - name: Seed database
      #   run: pnpm run db:seed

      # - name: Deploy migrations
      #   run: pnpm run db:migrate:deploy

      - name: Build application
        run: pnpm run build

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To Production Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}

          script: |
            cd instalflow-backend-service
            git pull origin main
            docker compose down
            docker build -t instalflow-backend-service:latest .
            docker compose up -d --build --remove-orphans

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy To Staging Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}

          script: |
            cd instalflow-backend-service
            git pull origin staging
            docker compose down
            docker build -t instalflow-backend-service:latest .
            docker compose up -d --build --remove-orphans
